### ISSUE TITLE
Add illumination info

### ISSUE THREAD

**Issue by chitgoks** [tomari/MoonCal#3]
Would be nice to have these info

Illumination
Distance
Age

Is it possible?

**Comment by tomari** [comment]
Thanks for feature requests.
Even though I don't find these info necessary, I always welcome pull requests!

**Comment by chitgoks** [comment]
Thank you for the reply

i think the others are doable but i believe illumination % is important so at least other moon phases like the waxing and waning can be identified as such. would this one property (illumination %) be possible to be added?
